---
- name: Allow 389ds_exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ ldap_389ds_exporter_web_listen_address.split(':')[1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"

- name: Write out config file
  template:
    src: 389ds_exporter.yml.j2
    dest: "{{ ldap_389ds_config_file }}"
    owner: "{{ ldap_389ds_exporter_system_user }}"
    group: "{{ ldap_389ds_exporter_system_group }}"
    mode: '0600'
  when: ldap_389ds_config_file is defined